//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_Ecommerce_Store1.HTML_Ecommerce_Store.Modules
{


    public partial class Header
    {
    }
}
