//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_Ecommerce_Store1.HTML_Ecommerce_Store
{


    public partial class _default
    {

        /// <summary>
        /// HeroSlider control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HTML_Ecommerce_Store1.HTML_Ecommerce_Store.Modules.HeroSlider HeroSlider;

        /// <summary>
        /// BannerTop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HTML_Ecommerce_Store1.HTML_Ecommerce_Store.Modules.BannerTop BannerTop;

        /// <summary>
        /// NewProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HTML_Ecommerce_Store1.HTML_Ecommerce_Store.Modules.NewProducts NewProducts;

        /// <summary>
        /// FeaturedProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HTML_Ecommerce_Store1.HTML_Ecommerce_Store.Modules.FeaturedProducts FeaturedProducts;

        /// <summary>
        /// TopProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HTML_Ecommerce_Store1.HTML_Ecommerce_Store.Modules.TopProducts TopProducts;
    }
}
